[tool.poetry]
name = "latch-top"
version = "0.1.0"
description = ""
authors = ["Ryan Teoh <ryan@latch.bio>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
psutil = "^5.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
